eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9700/eureka/
server:
  port: 9705
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    ttt:
      path: /ttt/**
      serviceId: service-feign
